# Generated by Django 5.0.1 on 2026-02-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(blank=True, max_length=100)),
                ('academic_year', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], max_length=20)),
                ('enrollment_date', models.DateField()),
                ('expected_graduation', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_credits', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_standing', models.CharField(choices=[('Good Standing', 'Good Standing'), ('Academic Probation', 'Academic Probation'), ("Dean's List", "Dean's List"), ("President's List", "President's List")], default='Good Standing', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
