# Generated by Django 5.0.1 on 2026-02-01 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('building', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('credits', models.IntegerField(default=3)),
                ('level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=20)),
                ('prerequisites', models.TextField(blank=True, help_text='List prerequisite courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Adjunct Professor', 'Adjunct Professor')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('office_location', models.CharField(max_length=100)),
                ('office_hours', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='professor_profiles/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='courses.department')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('section_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('semester', models.CharField(choices=[('Fall 2025', 'Fall 2025'), ('Spring 2026', 'Spring 2026'), ('Summer 2026', 'Summer 2026'), ('Fall 2026', 'Fall 2026')], max_length=20)),
                ('days', models.CharField(help_text='e.g., MWF, TR', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('max_capacity', models.IntegerField(default=30)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('waitlist_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='courses.professor')),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'ordering': ['semester', 'course__course_code'],
            },
        ),
    ]
