# Generated by Django 5.0.1 on 2026-02-01 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Waitlisted', 'Waitlisted'), ('Dropped', 'Dropped'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn')], default='Enrolled', max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('P', 'Pass'), ('I', 'Incomplete'), ('W', 'Withdrawn')], max_length=2, null=True)),
                ('midterm_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-semester', 'course_section__course__course_code'],
                'unique_together': {('student', 'course_section')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('Homework', 'Homework'), ('Quiz', 'Quiz'), ('Exam', 'Exam'), ('Project', 'Project'), ('Paper', 'Paper'), ('Presentation', 'Presentation'), ('Lab', 'Lab'), ('Participation', 'Participation')], max_length=50)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('points_possible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in final grade calculation', max_digits=5)),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('graded_date', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grades.enrollment')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_credits_earned', models.IntegerField(default=0)),
                ('total_credits_attempted', models.IntegerField(default=0)),
                ('academic_honors', models.TextField(blank=True, help_text="Dean's List, President's List, etc.")),
                ('generated_date', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='students.student')),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
            },
        ),
    ]
