# Generated by Django 5.0.1 on 2026-02-01 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship_type', models.CharField(choices=[('Academic Merit', 'Academic Merit'), ('Athletic', 'Athletic'), ('Need-Based', 'Need-Based'), ('Departmental', 'Departmental'), ('Diversity', 'Diversity'), ('Leadership', 'Leadership')], max_length=50)),
                ('minimum_gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('eligibility_requirements', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('renewable', models.BooleanField(default=False)),
                ('application_deadline', models.DateField()),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fees_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('on_payment_plan', models.BooleanField(default=False)),
                ('payment_plan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_status', models.CharField(choices=[('Current', 'Current'), ('Past Due', 'Past Due'), ('Hold', 'Hold - Cannot Register'), ('Paid in Full', 'Paid in Full')], default='Current', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='students.student')),
            ],
            options={
                'verbose_name': 'Financial Account',
                'verbose_name_plural': 'Financial Accounts',
            },
        ),
        migrations.CreateModel(
            name='FinancialAidPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('grants', models.DecimalField(decimal_places=2, default=0.0, help_text='Need-based grants', max_digits=10)),
                ('scholarships', models.DecimalField(decimal_places=2, default=0.0, help_text='Merit-based scholarships', max_digits=10)),
                ('loans', models.DecimalField(decimal_places=2, default=0.0, help_text='Student loans', max_digits=10)),
                ('work_study', models.DecimalField(decimal_places=2, default=0.0, help_text='Work-study award', max_digits=10)),
                ('total_aid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Awarded', 'Awarded'), ('Accepted', 'Accepted by Student'), ('Disbursed', 'Disbursed'), ('Declined', 'Declined')], default='Pending', max_length=50)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_aid_packages', to='students.student')),
            ],
            options={
                'verbose_name': 'Financial Aid Package',
                'verbose_name_plural': 'Financial Aid Packages',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Check', 'Check'), ('Bank Transfer', 'Bank Transfer'), ('Financial Aid', 'Financial Aid'), ('Payment Plan', 'Payment Plan')], max_length=50)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial_aid.financialaccount')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
