# Generated by Django 5.0.1 on 2026-02-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('Registration', 'Registration Period'), ('Classes', 'Classes Begin/End'), ('Exam', 'Examination Period'), ('Break', 'Academic Break'), ('Holiday', 'University Holiday'), ('Deadline', 'Important Deadline'), ('Commencement', 'Commencement Ceremony'), ('Orientation', 'Orientation'), ('Other', 'Other Event')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('semester', models.CharField(choices=[('Fall 2025', 'Fall 2025'), ('Spring 2026', 'Spring 2026'), ('Summer 2026', 'Summer 2026'), ('Fall 2026', 'Fall 2026')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Event',
                'verbose_name_plural': 'Academic Events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('academic_year', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('add_drop_deadline', models.DateField()),
                ('withdrawal_deadline', models.DateField()),
                ('final_exams_start', models.DateField()),
                ('final_exams_end', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UniversityHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='For multi-day holidays', null=True)),
                ('university_closed', models.BooleanField(default=True)),
                ('classes_cancelled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'University Holiday',
                'verbose_name_plural': 'University Holidays',
                'ordering': ['date'],
            },
        ),
    ]
